#!/usr/bin/env python3
"""Seed a GSD debug session from a triaged `dev test` issue, and print the
gsd-debugger spawn prompt.

Self-contained: stdlib only, plus the `gh` CLI. Owns its own extraction; does
not import anything from firestarter_app or the sibling triage skill.

    seed_debug_session.py 32                       # writes .planning/debug/<slug>.md
    seed_debug_session.py 32 --slug at28c256-sdp   # explicit slug
    seed_debug_session.py 32 --print-prompt-only
    seed_debug_session.py --body-file b.md --title "$T" --comment-file c.md --slug x

Why seeding matters: `devtest-triage` already ruled things out against the
datasheet. Those exclusions go into the session's `Eliminated` section so the
debugger does not re-derive them, and the fix-surface rules go into the spawn
prompt so it does not "fix" the GENERATED chip_database.json.

UNTRUSTED INPUT: issue and comment text is community-authored. It is size-bounded,
never eval'd, never shelled out, and written into the session file as data under a
`trigger:` field, exactly as /gsd-debug does.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone

REPO = "henols/firestarter_prom"
MAX_BODY = 1_000_000
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
TITLE_RE = re.compile(r"^\[dev test\]\s+(?P<chip>\S+)\s+[—-]\s+(?P<verdict>[A-Za-z]+)")
FENCE_RE = re.compile(r"```(?:json)?\s*\n(.*?)```", re.DOTALL)

# The fix-surface contract, handed to the debugger verbatim. Without this a
# debugger with Write access will "fix" the generated database and the change
# will vanish on the next regen.
GUARDRAILS = """\
<hard_constraints>
These are project rules. A fix that breaks one is wrong however well it works.

1. `firestarter_app/firestarter/data/chip_database.json` is GENERATED by
   `firestarter_app/tools/build_db.py`. NEVER edit it. Edits are erased on the
   next regen. Fix the generator, then regenerate.
2. The generator may not emit a field it cannot prove from minipro's
   `infoic.xml`. No invented fields, no per-chip lookup tables keyed on part
   number, no override stacks — three such guess tables were deliberately
   deleted in Phase 70. A wrong value is a wrong INTERPRETATION of an existing
   attribute (`flags`, `voltages`, `protocol_id`, `variant`, `pin_map`,
   `type`); fix the function that interprets it.
3. `firestarter/data/pinouts.json` is AUTHORED input to the generator, never
   written by it. A wrong socket wiring IS fixed there.
4. `tools/extra_chips.json` adds chips absent from infoic.xml ENTIRELY (2516,
   2532 today). It is not an override for a chip upstream already has.
5. Never weaken `tools/check_dispatch.py` (GATE-03) to make a change pass. It
   stops 12V reaching a 5V part's WE/address pin — a hardware-damage guard.
6. `firestarter/include/messages.h` is GENERATED from the meta repo's
   messages.toml. Never hand-edit.
7. Constants and flag bits are duplicated between
   `firestarter_app/firestarter/constants.py` and
   `firestarter/include/firestarter.h`. Change both together.

Verify a database change with:
  cd firestarter_app && python3 tools/build_db.py && python3 tools/diff_db.py \\
    && python3 tools/check_dispatch.py && python3 -m pytest -o addopts="" -q
`build_db.py` takes no arguments and regenerates on ANY invocation; it is
deterministic against the pinned SHA, so any diff is yours. A one-chip fix that
moves hundreds of chips means the decode change was too broad.
</hard_constraints>

<hardware>
A firmware or write-path fix CANNOT be confirmed without a chip on the bench.
`firestarter dev test <chip>` ALWAYS WRITES to the chip. Do not run it, or any
other hardware command, without the operator's explicit go-ahead in this
session — and never run one while another debugger may hold the serial port.
State plainly what remains unverified rather than implying a fix is confirmed.
</hardware>
"""


def _repo_root() -> str:
    """Locate the checkout from this file: <root>/.claude/skills/<s>/scripts/.

    Falls back to the current directory when the skill is installed outside a
    checkout, where an explicit flag or env override is the only sane source.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.normpath(os.path.join(here, *[os.pardir] * 4))
    return root if os.path.isdir(os.path.join(root, "firestarter_app")) else os.getcwd()


def detect_gsd(root: str) -> tuple[bool, str]:
    """(gsd_debugger_available, directory for the record).

    GSD is optional. The `gsd-debugger` subagent resolves from `.claude/agents/`
    in the project or `~/.claude/agents/`; if neither has it, spawning that
    subagent type fails, so the skill must fall back to a plain investigation.
    The directory choice is independent: `.planning/debug/` is the right home
    whenever `.planning/` exists, GSD agent or not.
    """
    candidates = [
        os.path.join(root, ".claude", "agents", "gsd-debugger.md"),
        os.path.expanduser("~/.claude/agents/gsd-debugger.md"),
    ]
    available = any(os.path.exists(c) for c in candidates)
    if os.path.isdir(os.path.join(root, ".planning")):
        directory = os.path.join(root, ".planning", "debug")
    else:
        directory = os.path.join(root, "devtest-investigations")
    return available, directory


def gh(args: list[str]) -> str:
    try:
        r = subprocess.run(["gh", *args], capture_output=True, text=True,
                           timeout=120, check=False)
    except FileNotFoundError:
        sys.exit("error: `gh` not found — install the GitHub CLI")
    except subprocess.TimeoutExpired:
        sys.exit("error: `gh` timed out")
    if r.returncode != 0:
        sys.exit(f"error: gh {' '.join(args)} failed: {r.stderr.strip()[:400]}")
    return r.stdout


def extract_report(body: str) -> dict | None:
    for block in FENCE_RE.findall((body or "")[:MAX_BODY]):
        try:
            obj = json.loads(block)
        except (json.JSONDecodeError, ValueError, RecursionError):
            continue
        if isinstance(obj, dict) and "schema_version" in obj:
            return obj
    return None


def parse_eliminated(comment: str) -> list[tuple[str, str]]:
    """Pull MATCH rows out of a devtest-triage cross-check table.

    Row shape: | Check | Datasheet | Database | Verdict |
    A verdict beginning MATCH means triage proved that hypothesis dead — it
    becomes an `Eliminated` entry so the debugger does not re-check it.
    """
    out = []
    for line in (comment or "")[:MAX_BODY].splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            continue
        check, datasheet, database, verdict = cells[0], cells[1], cells[2], cells[3]
        if not verdict.upper().startswith("MATCH"):
            continue
        if check.lower() in ("check", "---") or set(check) <= set("-: "):
            continue
        out.append((
            f"{check} is wrong",
            f"datasheet says {datasheet}; database has {database} — triage "
            f"cross-check verdict {verdict}",
        ))
    return out


def make_slug(chip: str, steps: list[str], explicit: str | None) -> str:
    if explicit:
        s = explicit.strip()
    else:
        tail = steps[0].replace("-", "") if steps else "fail"
        s = f"{chip}-{tail}"
    s = re.sub(r"[^a-z0-9-]+", "-", s.lower()).strip("-")[:30].strip("-")
    if not SLUG_RE.match(s):
        sys.exit(f"error: could not build a valid slug from {s!r}")
    return s


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("number", nargs="?", type=int, help="issue number")
    ap.add_argument("--repo", default=REPO)
    ap.add_argument("--slug")
    ap.add_argument("--root", default=_repo_root(),
                    help="repo root holding .planning (default: the checkout "
                         "this skill lives in)")
    ap.add_argument("--title", help="offline mode: issue title")
    ap.add_argument("--body-file", help="offline mode: issue body")
    ap.add_argument("--comment-file", help="offline mode: triage comment")
    ap.add_argument("--print-prompt-only", action="store_true",
                    help="do not write the session file")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing session file")
    ap.add_argument("--mode", choices=["auto", "gsd", "standalone"], default="auto",
                    help="auto (default) uses GSD only when a gsd-debugger agent "
                         "is installed; standalone never depends on GSD")
    args = ap.parse_args()

    # ---- gather -----------------------------------------------------------
    if args.number is not None:
        title = gh(["issue", "view", str(args.number), "--repo", args.repo,
                    "--json", "title", "-q", ".title"]).strip()
        body = gh(["issue", "view", str(args.number), "--repo", args.repo,
                   "--json", "body", "-q", ".body"])
        raw = gh(["issue", "view", str(args.number), "--repo", args.repo,
                  "--json", "comments"])
        try:
            comments = json.loads(raw).get("comments", [])
        except (json.JSONDecodeError, AttributeError):
            comments = []
        triage = ""
        for c in comments:
            cbody = (c or {}).get("body", "")
            if "Datasheet cross-check" in cbody:
                triage = cbody
    else:
        if not (args.body_file and args.title):
            sys.exit("error: pass an issue NUMBER, or --title with --body-file")
        title = args.title
        with open(args.body_file, encoding="utf-8", errors="replace") as f:
            body = f.read(MAX_BODY + 1)
        triage = ""
        if args.comment_file:
            with open(args.comment_file, encoding="utf-8", errors="replace") as f:
                triage = f.read(MAX_BODY + 1)

    t = TITLE_RE.match((title or "").strip())
    report = extract_report(body)
    if not t or not report:
        sys.exit("error: not a parseable `dev test` issue "
                 f"(title marker: {'yes' if t else 'no'}, "
                 f"report: {'yes' if report else 'no'})")

    chip = t.group("chip")
    verdict = t.group("verdict").upper()
    auto = report.get("auto_capture") or {}
    volt = report.get("voltage") or {}
    steps = report.get("steps") or []
    failing = [s for s in steps if isinstance(s, dict)
               and str(s.get("verdict", "")).upper() in ("BAD", "MARGINAL")]
    bad = [str(s.get("op")) for s in failing]
    # Reasons from FAILING steps only. An NA step's reason ("no chip-id in DB
    # entry", "UV-EPROM has no electrical erase") explains why a step did not
    # apply — quoting it as an error sends the debugger after a non-problem.
    errors = "; ".join(
        f"{s.get('op')}: {s.get('reason')}" for s in failing if s.get("reason")
    ) or "none recorded (failing steps carried no reason string)"
    if not bad:
        where = f"#{args.number}" if args.number is not None else f"this {chip} report"
        sys.exit(f"error: no BAD/marginal step in {where} — a PASS report is "
                 "`devtest-triage` territory (close + log), not a debug session")

    slug = make_slug(chip, bad, args.slug)
    eliminated = parse_eliminated(triage)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    issue_ref = f"#{args.number}" if args.number is not None else "(offline)"

    # ---- session file -----------------------------------------------------
    elim_block = "\n".join(
        f"- hypothesis: {h}\n  evidence: {e}\n  timestamp: {now[:10]}\n"
        for h, e in eliminated
    ) or "(none — triage left no MATCH rows to carry over)\n"

    session = f"""---
status: investigating
trigger: "community dev test issue {issue_ref}: {chip} — {verdict}; failing steps: {', '.join(bad)}"
created: {now}
updated: {now}
---

## Current Focus

hypothesis: (none yet — gather evidence first)
test: read the code path for the failing step on protocol {auto.get('protocol')}
expecting: a defect in decode, host, or firmware — see the fix-surface rules
next_action: gather initial evidence

## Symptoms

expected: every applicable `dev test` step reports OK for {chip}
actual: {', '.join(bad)} reported {verdict} (report schema {report.get('schema_version')})
errors: {errors}
reproduction: firestarter dev test {chip}  (ALWAYS WRITES — operator go-ahead required)
started: report generated {report.get('generated')}; host {auto.get('host_version')}, hw {auto.get('hw_revision')}

## Context

chip: {chip}
protocol: {auto.get('protocol')}
chip_id expected/actual: {auto.get('chip_id_expected')} / {auto.get('chip_id_actual')}
voltage: vpp {volt.get('vpp_before_mv')} -> {volt.get('vpp_after_mv')} mV, vpe {volt.get('vpe_before_mv')} -> {volt.get('vpe_after_mv')} mV
dedup_fingerprint: {report.get('dedup_fingerprint')}
issue: {issue_ref}

## Eliminated

{elim_block}
## Evidence

"""

    gsd_available, directory = detect_gsd(args.root)
    mode = args.mode
    if mode == "auto":
        mode = "gsd" if gsd_available else "standalone"
    elif mode == "gsd" and not gsd_available:
        print("warning: --mode gsd forced, but no gsd-debugger agent found in "
              f"{args.root}/.claude/agents/ or ~/.claude/agents/. Spawning that "
              "subagent type will fail.", file=sys.stderr)

    path = os.path.join(directory, f"{slug}.md")
    if not args.print_prompt_only:
        if os.path.exists(path) and not args.force:
            sys.exit(f"error: {path} already exists — pass --force to overwrite, "
                     f"or resume it instead")
        os.makedirs(directory, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(session)
        label = "Session" if mode == "gsd" else "Investigation record"
        print(f"[{mode}] {label}: {path}")
        print(f"[{mode}] Status: investigating")
        print(f"[{mode}] Carried over {len(eliminated)} eliminated hypothes"
              f"{'is' if len(eliminated) == 1 else 'es'} from triage")
        if mode == "standalone":
            print("[standalone] GSD not detected — emitting a plain investigation "
                  "prompt with no gsd-debugger dependency.")

    # ---- prompt -----------------------------------------------------------
    shared_head = f"""<objective>
Investigate issue: {slug}

**Summary:** community `dev test` reports {', '.join(bad)} = {verdict} for {chip}
on protocol {auto.get('protocol')}. The datasheet cross-check is already done and
recorded under Eliminated in the record file — do not repeat it.
</objective>

<symptoms>
expected: every applicable `dev test` step reports OK for {chip}
actual: {', '.join(bad)} reported {verdict}
errors: {errors}
reproduction: firestarter dev test {chip}
timeline: host {auto.get('host_version')}, report {report.get('generated')}
</symptoms>
"""

    if mode == "gsd":
        prompt = shared_head + f"""
<mode>
symptoms_prefilled: true
goal: find_and_fix
</mode>

<debug_file>
RESUME an existing session. Do NOT run `create_debug_file`, and do NOT overwrite
this file — it is already seeded and creating a new one discards the work below.

path:   {path}
status: investigating

Enter at the `resume_from_file` step: read the full file, then continue
`investigation_loop` from Current Focus. Symptoms and Context are already
populated (Symptoms is IMMUTABLE). Eliminated is already populated and is
APPEND-only — every hypothesis listed there was disproved against the chip's
datasheet by the triage step. Re-checking one is wasted work.
</debug_file>

{GUARDRAILS}"""
        banner = [
            'Spawn gsd-debugger DIRECTLY with this prompt (subagent_type="gsd-debugger").',
            "Do NOT spawn gsd-debug-session-manager — nested spawning is broken in",
            "this devcontainer and orphans a second debugger onto the same hardware.",
        ]
    else:
        prompt = shared_head + f"""
<record_file>
Read, then keep updated as you work: {path}

It is already populated. Treat the sections as:
  Symptoms   — IMMUTABLE, do not rewrite
  Context    — the chip, protocol, voltages and issue reference
  Eliminated — APPEND-only. Every hypothesis listed was disproved against the
               chip's datasheet during triage. Re-checking one is wasted work.
  Evidence   — APPEND a dated entry for each thing you check and what you found

Before each action, overwrite Current Focus with your live hypothesis, the test,
what a result would mean, and the concrete next action. That block is what lets
this be picked up after a context reset.
</record_file>

<method>
Work one hypothesis at a time. State it, name the single test that would disprove
it, run that test, then either move it to Eliminated with the evidence, or narrow.
Do not change code until a hypothesis survives its disproving test.
</method>

{GUARDRAILS}"""
        banner = [
            ("GSD is not installed — this is a standalone investigation prompt."
             if not gsd_available else
             "Standalone mode (forced) — this prompt has no GSD dependency."),
            "Hand it to a general-purpose agent, or work it yourself against the",
            "record file. Commit any fix atomically on its own branch.",
        ]

    print("\n" + "=" * 72)
    for line in banner:
        print(line)
    print("=" * 72 + "\n")
    print(prompt)
    return 0


if __name__ == "__main__":
    sys.exit(main())
