/*
 * Project Name: Firestarter
 * Copyright (c) 2024 Henrik Olsson
 *
 * Permission is hereby granted under MIT license.
 *
 * Firestarter -- v1.2 log-message catalog (C++ firmware side)
 *
 * DO NOT EDIT -- generated by tools/catalog/codegen.py from
 *               tools/catalog/messages.toml.
 * Re-run codegen after editing the canonical catalog.
 *
 * Catalog version: 1
 * Total messages: 71
 */

#ifndef __MESSAGES_H__
#define __MESSAGES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <avr/pgmspace.h>

// --- Severity codes (mirrors host catalog) ---
#define MSG_SEVERITY_OK    0x01
#define MSG_SEVERITY_INIT  0x02
#define MSG_SEVERITY_MAIN  0x03
#define MSG_SEVERITY_END   0x04
#define MSG_SEVERITY_INFO  0x05
#define MSG_SEVERITY_WARN  0x06
#define MSG_SEVERITY_ERROR 0x07
#define MSG_SEVERITY_DATA  0x08

// --- Message IDs (sorted ascending) ---
#define MSG_NONE                       0x00
#define MSG_OK_READY                   0x01
#define MSG_OK_REQ_DATA                0x02
#define MSG_OK_FW_VERSION              0x03
#define MSG_OK_REV                     0x04
#define MSG_OK_CFG                     0x05
#define MSG_OK_FW_HANDSHAKE            0x06
#define MSG_INIT_DONE                  0x10
#define MSG_MAIN_DONE                  0x20
#define MSG_END_DONE                   0x30
#define MSG_INFO_MAIN_START            0x40
#define MSG_INFO_MAIN_DONE             0x41
#define MSG_INFO_INIT_START            0x42
#define MSG_INFO_END_START             0x43
#define MSG_INFO_BUF_VAL               0x44
#define MSG_INFO_TOKEN_COUNT           0x45
#define MSG_INFO_FLAG_FORCE            0x46
#define MSG_INFO_FLAG_CAN_ERASE        0x47
#define MSG_INFO_FLAG_SKIP_ERASE       0x48
#define MSG_INFO_FLAG_SKIP_BLANK       0x49
#define MSG_INFO_FLAG_VPE_AS_VPP       0x4A
#define MSG_INFO_FLAG_OUTPUT_EN        0x4B
#define MSG_INFO_FLAG_CHIP_EN          0x4C
#define MSG_INFO_BUFFER_SIZE           0x4D
#define MSG_INFO_MEM_SIZE              0x4E
#define MSG_INFO_ADDR_MASK             0x4F
#define MSG_INFO_MATCH_LINES           0x50
#define MSG_INFO_RETRIES               0x51
#define MSG_INFO_REG_HEADER            0x52
#define MSG_INFO_BIT_HEADER            0x53
#define MSG_INFO_BIT_STR               0x54
#define MSG_INFO_CE_OE                 0x55
#define MSG_INFO_ADDR                  0x56
#define MSG_INFO_ADDR_REMAP            0x57
#define MSG_INFO_SKIPPING_ERASE        0x58
#define MSG_INFO_SKIPPING_ERASE_MEM    0x59
#define MSG_WARN_REV0_VPP_UNSUPPORTED  0x80
#define MSG_WARN_VPP_LOW               0x81
#define MSG_WARN_VPP_HIGH              0x82
#define MSG_WARN_CHIP_ID_MISMATCH      0x83
#define MSG_WARN_MEM_SIZE_TOO_SMALL    0x84
#define MSG_ERR_BAD_JSON               0xA0
#define MSG_ERR_NO_CMD                 0xA1
#define MSG_ERR_SETUP                  0xA2
#define MSG_ERR_PARSE_CFG              0xA3
#define MSG_ERR_EMPTY_INPUT            0xA4
#define MSG_ERR_NOT_SUPPORTED          0xA5
#define MSG_ERR_NO_CHIP_ID             0xA6
#define MSG_ERR_OUT_OF_RANGE           0xA7
#define MSG_ERR_TIMEOUT                0xA8
#define MSG_ERR_DATA_ERR_N             0xA9
#define MSG_ERR_CMD_TIMEOUT            0xAA
#define MSG_ERR_UNKNOWN_CMD            0xAB
#define MSG_ERR_REV0_VPP_RD            0xAC
#define MSG_ERR_CMD                    0xAD
#define MSG_ERR_MEM_TYPE_UNSUPPORTED   0xAE
#define MSG_ERR_VERIFY                 0xAF
#define MSG_ERR_NOT_BLANK              0xB0
#define MSG_ERR_WRITE_FAILED           0xB1
#define MSG_ERR_EEPROM_TIMEOUT         0xB2
#define MSG_ERR_FL4_VERIFY_TIMEOUT     0xB3
#define MSG_ERR_INTEL_VPP              0xB4
#define MSG_ERR_INTEL_PROGRAM          0xB5
#define MSG_ERR_INTEL_SR_TIMEOUT       0xB6
#define MSG_ERR_OP_TIMEOUT             0xB7
#define MSG_ERR_VPP_HIGH               0xB8
#define MSG_ERR_CHIP_ID_MISMATCH       0xB9
#define MSG_ERR_MEM_SIZE_TOO_SMALL     0xBA
#define MSG_DATA_PROGRESS              0xE0
#define MSG_DATA_VOLTAGE               0xE1
#define MSG_DATA_SENDING               0xE2

// --- Param-count lookup (PROGMEM table, 256 bytes flat) ---
// MSG_PARAM_COUNT(id) returns the wire-byte count of the params for the
// given ID, or 0xFF for unallocated IDs or variable-length (ascii_str)
// payloads. Callers needing fixed-shape byte counts at compile time
// should consult the catalog directly.
extern const uint8_t MSG_PARAM_BYTES_TABLE[256] PROGMEM;

#define MSG_PARAM_COUNT(id) ((uint8_t)pgm_read_byte(&MSG_PARAM_BYTES_TABLE[(id)]))

#ifdef __cplusplus
}
#endif

#endif  // __MESSAGES_H__
