/* DO NOT EDIT -- generated by tools/gen_sdp_bus_config.py
 * Re-run after editing firestarter_app/firestarter/data/pinouts.json */

#pragma once

#include <stdint.h>
#include "firestarter.h"

#define SDP_BUS_CONFIG_COUNT 5

typedef struct {
    const char* chip_name;
    const char* pinout_name;
    uint32_t mem_size;
    bus_config_t bus_config;
} sdp_bus_config_row_t;

static const sdp_bus_config_row_t SDP_BUS_CONFIGS[] = {
    {
        "AT28C256",
        "DIP28_28C256",
        32768UL,
        {
            { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0F, 0xFF },
            0x0000BFFFUL,
            14,
            14,
            0xFF,
            0x00000000UL
        }
    },
    {
        "AT28C64",
        "DIP28_28C64",
        8192UL,
        {
            { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0xFF },
            0x00001FFFUL,
            13,
            14,
            0xFF,
            0x00000000UL
        }
    },
    {
        "AT28C16",
        "DIP24_2816",
        2048UL,
        {
            { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0xFF },
            0x000007FFUL,
            11,
            11,
            0xFF,
            0x00000000UL
        }
    },
    {
        "AT28C010",
        "DIP32_28C512_EEPROM",
        131072UL,
        {
            { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0xFF },
            0x0000FFFFUL,
            16,
            20,
            0xFF,
            0x00000000UL
        }
    },
    {
        "AT28C040",
        "DIP32_28C512_EEPROM",
        524288UL,
        {
            { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0xFF },
            0x0000FFFFUL,
            16,
            20,
            0xFF,
            0x00000000UL
        }
    },
};
