/* DO NOT EDIT -- generated by tools/gen_validation_header.py
 * Re-run after editing tools/validation_matrix_spec.json */

#pragma once

#include <stdint.h>

#define VAL_FAMILY_COUNT 13

typedef struct {
    uint32_t protocol;
    const char* family_id;
    const char* handler_name;
} val_family_entry_t;

static const val_family_entry_t VAL_FAMILIES[] = {
    { 0x07, "eprom", "configure_eprom" },
    { 0x08, "eprom", "configure_eprom" },
    { 0x0B, "eprom", "configure_eprom" },
    { 0x0D, "eeprom28c", "configure_eeprom28c" },
    { 0x06, "flash3", "configure_flash3" },
    { 0x05, "flash4", "configure_flash4" },
    { 0x35, "flash4", "configure_flash4" },
    { 0x39, "flash4", "configure_flash4" },
    { 0x10, "flash_intel", "configure_flash_intel" },
    { 0x0E, "sram", "configure_sram" },
    { 0x27, "sram", "configure_sram" },
    { 0x28, "sram", "configure_sram" },
    { 0x29, "sram", "configure_sram" },
};
