/*
 * Project Name: Firestarter
 * Copyright (c) 2024 Henrik Olsson
 *
 * Permission is hereby granted under MIT license.
 *
 * Phase 52 Plan 02 — Firmware Unity vector suite.
 *
 * Asserts both legs of the COBS frame contract against the frozen golden
 * vectors generated in Plan 01 (firestarter/include/frame_vectors.h):
 *
 *   Leg 1 (encode):  build_cobs_frame_bytes(vec.payload) == vec.frame
 *   Leg 2 (decode):  rurp_communication_read_data(vec.frame) == vec.payload
 *
 * A CRC8 known-answer test (D-06/SC4) pins poly 0x07 / seed 0x00
 * independently of the production CRC8_TABLE PROGMEM array.
 *
 * Decode leg constraint (CR-01): rurp_communication_read_data() caps at
 * DATA_BUFFER_SIZE - 1 = 511 bytes. Vectors with payload_len > 511 are
 * encoder-only; the decode loop skips them (Pitfall 5 / RESEARCH §5.5).
 *
 * Mirrors the structure of test_cobs_cmd_frame.cpp (Phase 51 Plan 01).
 * Uses serial_read_mock.h for the decode leg (finite-stream semantics).
 *
 * Requirements pinned: LOCK-01, LOCK-02 (SC2/SC4).
 */

#include <Arduino.h>
#include <ArduinoFake.h>
#include <unity.h>

#include <cstdint>
#include <cstddef>
#include <cstring>
#include <vector>

/* Shared mock helper — wires Serial.read/available/peek to a queued vector. */
#include "serial_read_mock.h"

extern "C" {
#include "rurp_shield.h"
#include "firestarter.h"
}

/* Golden-vector PROGMEM catalog (generated by tools/catalog/codegen_vectors.py). */
#include "frame_vectors.h"

using namespace fakeit;

/* ------------------------------------------------------------------------ */
/* Shared test state                                                         */
/* ------------------------------------------------------------------------ */

static char data_buffer[DATA_BUFFER_SIZE];
static std::vector<uint8_t> rx_queue;
static size_t rx_pos;

/* ------------------------------------------------------------------------ */
/* Reference CRC8 (poly 0x07, seed 0x00, no refl, no XOR) — table-free.    */
/* Copied from test_cobs_cmd_frame.cpp so this suite is fully independent   */
/* of the production CRC8_TABLE in rurp_serial_utils.cpp.                   */
/* ------------------------------------------------------------------------ */
static uint8_t ref_crc8(const uint8_t* data, size_t n) {
    uint8_t crc = 0;
    for (size_t i = 0; i < n; i++) {
        crc ^= data[i];
        for (int k = 0; k < 8; k++) {
            crc = (crc & 0x80)
                      ? (uint8_t)((crc << 1) ^ 0x07)
                      : (uint8_t)(crc << 1);
        }
    }
    return crc;
}

/* ------------------------------------------------------------------------ */
/* COBS encode helper — test-side only, used to build expected byte streams. */
/*                                                                           */
/* Encodes `src[0..len-1]` into `dst`, returns encoded byte count (without  */
/* the trailing 0x00 delimiter — caller appends it).                        */
/*                                                                           */
/* Standard COBS: scan for 0x00 or end of run (≤254 non-zero bytes), emit  */
/* run-code byte (run_len+1), then the non-zero bytes.  A 0x00 payload byte */
/* emits a run-code of 1 with no data bytes.  A 254-run code byte is 0xFF   */
/* (no implicit zero follows it per RFC COBS).                               */
/* ------------------------------------------------------------------------ */
static size_t test_cobs_encode(const uint8_t* src, size_t len, uint8_t* dst) {
    size_t out = 0;
    size_t code_pos = out++;        /* placeholder for first run-code */
    uint8_t code = 1;               /* run_len + 1 */

    for (size_t i = 0; i < len; i++) {
        if (src[i] == 0x00) {
            dst[code_pos] = code;
            code_pos = out++;
            code = 1;
        } else {
            dst[out++] = src[i];
            code++;
            if (code == 0xFF) {
                /* 254-run boundary: emit now, start new run without zero */
                dst[code_pos] = code;
                code_pos = out++;
                code = 1;
            }
        }
    }
    dst[code_pos] = code;
    return out;
}

/* Build the COBS frame byte sequence (no '#' preamble for command frames) into
 * `out_vec`:
 *   COBS(payload + CRC8(payload)) + 0x00
 * This is what rurp_communication_read_data() receives on the command channel. */
static void build_cobs_frame_bytes(
    const uint8_t* payload, size_t payload_len,
    std::vector<uint8_t>& out_vec
) {
    uint8_t crc = ref_crc8(payload, payload_len);

    /* Logical stream = payload + crc byte */
    std::vector<uint8_t> src(payload, payload + payload_len);
    src.push_back(crc);

    /* COBS-encode: max encoded size = len + len/254 + 1 */
    size_t max_enc = src.size() + src.size() / 254 + 2;
    std::vector<uint8_t> encoded(max_enc);
    size_t enc_len = test_cobs_encode(src.data(), src.size(), encoded.data());

    out_vec.insert(out_vec.end(), encoded.data(), encoded.data() + enc_len);
    out_vec.push_back(0x00);  /* frame delimiter */
}

/* ------------------------------------------------------------------------ */
/* setUp / tearDown                                                          */
/* ------------------------------------------------------------------------ */

static unsigned long millis_counter;

void setUp(void) {
    ArduinoFakeReset();
    rx_queue.clear();
    rx_pos = 0;
    millis_counter = 0;
    memset(data_buffer, 0, sizeof(data_buffer));

    /* Stub flush() so ArduinoFake doesn't warn. */
    When(Method(ArduinoFake(Serial), flush)).AlwaysReturn();

    /* Stub write so ArduinoFake doesn't complain if the decode path ever
     * triggers an error log that touches Serial.write (shouldn't, but safe). */
    When(OverloadedMethod(ArduinoFake(Serial), write, size_t(uint8_t)))
        .AlwaysReturn((size_t)1);

    /* millis() — monotonically increasing counter.  The COBS decoder does
     * NOT have a wall-clock timeout loop (the 2 s cascade was deleted in
     * Phase 50 — SC1 win).  This stub is retained for defensive
     * completeness in case any helper path ever calls millis(). */
    When(Method(ArduinoFake(Function), millis))
        .AlwaysDo([&]() -> unsigned long {
            millis_counter += 100;
            return millis_counter;
        });
}

void tearDown(void) {
}

/* ------------------------------------------------------------------------ */
/* main — Wave-0 scaffold (compiles + links cleanly; no RUN_TEST yet)       */
/* ------------------------------------------------------------------------ */
int main(int argc, char** argv) {
    (void)argc;
    (void)argv;
    UNITY_BEGIN();
    UNITY_END();
    return 0;
}
